services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - ls
        - for i in `find org -name "*.class"`; do
          javap $i | grep DefaultMain >/dev/null;
          if [ $? -eq 0 ]; then
          remover="org/combinators/solitaire/";
          i_without=${i#$remover};
          i_cleaned=${i_without%\$*};
          variant=${i_cleaned////.};
          echo $variant;
          fi
          done