env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "$GENERATE.archway.ArchwayMain"
         - mv target/solitaire/src/main/java/org/combinators/solitaire/* nextgen-solitaire/src/test/java


