env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "$GENERATE.archway.ArchwayMain"
         - sbt "$GENERATE.bakersdozen.BakersDozenMain"
         - sbt "$GENERATE.bakersdozen.SpanishPatienceMain"
         - sbt "$GENERATE.bakersdozen.CastlesInSpainMain"
         - sbt "$GENERATE.bigforty.BigFortyMain"
         - sbt "$GENERATE.castle.CastleMain"
         - sbt "$GENERATE.delta.BakersDozenMain"
         - sbt "$GENERATE.fan.FanMain"
         - sbt "$GENERATE.fan.FanFreeMain"
         - sbt "$GENERATE.fan.ScotchPatienceMain"
         - sbt "$GENERATE.fan.ShamrocksMain"
         - sbt "$GENERATE.fan.FanTwoDeckMain"
         - sbt "$GENERATE.fan.FanEasyDeckMain"
         - sbt "$GENERATE.fan.LaBelleLucieMain"
         - sbt "$GENERATE.fan.SuperFlowerGardenMain"
         - sbt "$GENERATE.fan.TrefoilMain"
         - sbt "$GENERATE.fan.AlexanderTheGreatMain"
         - sbt "$GENERATE.freecell.FreeCellMain"
         - sbt "$GENERATE.golf.GolfMain"
         - sbt "$GENERATE.golf.GolfNoWrapMain"
         - sbt "$GENERATE.golf.AllInARowMain"
         - sbt "$GENERATE.golf.FlakeMain"
         - sbt "$GENERATE.golf.FlakeTwoDecksMain"
         - sbt "$GENERATE.golf.RobertMain"
         - sbt "$GENERATE.gypsy.GypsyMain"
         - sbt "$GENERATE.gypsy.GiantMain"
         - sbt "$GENERATE.gypsy.NomadMain"
         - sbt "$GENERATE.gypsy.EastHavenMain"
         - sbt "$GENERATE.gypsy.IrmgardMain"
         - sbt "$GENERATE.gypsy.MilliganMain"
         - sbt "$GENERATE.idiot.IdiotMain"
         - sbt "$GENERATE.klondike.KlondikeMain"
         - sbt "$GENERATE.minimal.MinimalSingleMain"
         - sbt "$GENERATE.minimal.MinimalMultiMain"
         - sbt "$GENERATE.napoleon.NapoleonMain"
         - sbt "$GENERATE.narcotic.NarcoticMain"
         - sbt "$GENERATE.simplesimon.SimpleSimonMain"
         - sbt "$GENERATE.simplesimon.SimpleVarMain"
         - sbt "$GENERATE.spider.SpiderMain"
         - sbt "$GENERATE.spider.SpideretteMain"
         - sbt "$GENERATE.spider.ScorpionMain"
         - sbt "$GENERATE.spider.MrsMopMain"
         - sbt "$GENERATE.spider.GiganticMain"
         - sbt "$GENERATE.spider.SpiderwortMain"
         - sbt "$GENERATE.spider.BabyMain"
         - sbt "$GENERATE.spider.OpenSpiderMain"
         - sbt "$GENERATE.spider.OpenScorpionMain"
         - sbt "$GENERATE.spider.CurdsAndWheyMain"

