env:
  global:
    - GENERATE="runMain org.combinators.solitaire"

matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "runMain org.combinators.solitaire.travis.archwayTest"
         - sbt "runMain org.combinators.solitaire.travis.bakersDozenTest"
         - sbt "runMain org.combinators.solitaire.golf.GolfMain"
         - sbt "$GENERATE.fan.FanMain"
         - sbt $GENERATE.fan.FanFreeMain
