matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "runMain org.combinators.solitaire.travis.archwayTest"
         - sbt "runMain org.combinators.solitaire.travis.bakersDozenTest"
