env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "$GENERATE.fan.FanMain"
         - sbt "testOnly file:/home/travis/build/gilchristb78/nextgen-solitaire/target/src/main/java/org/combinators/solitaire/fan/*"


