services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - sbt compile
        - pwd
        - ls
        - sbt "$GENERATE.fan.FanMain"
        - sbt "$GENERATE.bakersdozen.BakersDozenMain"
        - sbt "$GENERATE.gypsy.GiantMain"
        - sbt clean compile
        - mv -f generated/src/main/java/org/combinators/solitaire/* src/test/java/org/combinators/solitaire/
        - sbt test