env:
  global:
    - TESTINGER="runMain org.combinators.solitaire"
    - Generate="sbt runMain org.combinators.solitaire"
    - Generate2="runMain org.combinators.solitaire"
    - generate ="sbt runMain org.combinators.solitaire."
    - generate_="sbt runMain org.combinators.solitaire."
matrix:
   include:
       - language: scala
         jdk: openjdk8
         script:
         - sbt compile
         - sbt "runMain org.combinators.solitaire.travis.archwayTest"
         - sbt "runMain org.combinators.solitaire.travis.bakersDozenTest"
         - sbt "runMain org.combinators.solitaire.golf.GolfMain"
         - sbt "$TESTINGER.fan.FanMain"
         - sbt $TESTERINGER.fan.FanFreeMain
         - $Generate.fan.ScotchPatienceMain
         - sbt $Generate2.fan.FanTwoDeckMain
         - $generate fan.FanMain
         - $generate_fan.FanMain