env:
  global:
    - TEST_DIR="/home/travis/test"

matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - sbt compile
        - sbt "runMain org.combinators.solitaire.fan.FanMain"
        - cp -r $TEST_DIR/* /home/travis/build/yourusername/yourrepository/target/
        - sbt testOnly /home/travis/build/yourusername/yourrepository/target/*