services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - sbt compile
        - cd target/scala-2.12/classes/
        - pwd
        - ls
        - for i in `find org -name "*.class"`; do
          javap $i | grep DefaultMain >/dev/null;
          if [ $? -eq 0 ]; then
          remover="org/combinators/solitaire/";
          i_without=${i#$remover};
          i_cleaned=${i_without%\$*};
          variant=${i_cleaned////.};
          echo $variant;
          cd ../../..;
          sbt "$GENERATE.$variant";
          mv -f generated/src/main/java/org/combinators/solitaire/* src/test/java/org/combinators/solitaire/;
          if sbt test; then
          mv src/test/java/org/combinators/solitaire/* generated/yes; else
          mv src/test/java/org/combinators/solitaire/* generated/no;
          fi;
          cd target/scala-2.12/classes/;
          fi;
          done
        - cd ../../../generated/yes
        - ls
        - cd ../no
        - ls
