services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - sbt compile
        - pwd
        - ls
        - while read i; do
          variant=$(echo "$i" | tr -d '\n');
          echo $variant;
          sbt "$GENERATE.$variant";
          mv -f generated/src/main/java/org/combinators/solitaire/* src/test/java/org/combinators/solitaire/;
          if sbt test; then
          mv src/test/java/org/combinators/solitaire/* Valid; else
          mv src/test/java/org/combinators/solitaire/* Invalid;
          fi;
          done < travis.txt
        - cd Valid
        - git config --global user.email "gilchristb78@gmail.com";
        - git config --global user.name "gilchristb78";
        - git add .;
        - git commit -m "Travis build update: Valid directory";
        - git push "https://${GH_TOKEN}@github.com/gilchristb78/Valid" HEAD:main;
        - ls
        - cd ../Invalid
        - ls
