env:
  global:
    - GENERATE="runMain org.combinators.solitaire"
matrix:
  include:
    - language: scala
      jdk: openjdk8
      script:
        - sbt compile
        - pwd
        - ls
        - sbt "$GENERATE.fan.FanMain"
        - sbt clean compile
        - ls -R
        - sbt "testOnly file:./generated/src/main/java/org/combinators/solitaire/fan/*"