.PHONY: freecell
freecell: freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java
	javac -cp standAlone.jar:./freecell/src/main/java freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java
	javac -cp standAlone.jar:./freecell/src/main/java freecell/src/main/java/org/combinators/solitaire/freecell/model/*.java

run-freecell: freecell
	java -cp standAlone.jar:./freecell/src/main/java org/combinators/solitaire/freecell/FreeCell

.PHONY: narcotic
narcotic: narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java
	javac -cp standAlone.jar:./narcotic/src/main/java narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java

run-narcotic: narcotic
	java -cp standAlone.jar:./narcotic/src/main/java org/combinators/solitaire/narcotic/Narcotic

.PHONY: stalactites
stalactites: stalactites/src/main/java/org/combinators/solitaire/stalactites/Stalactites.java
	javac -cp standAlone.jar:./stalactites/src/main/java stalactites/src/main/java/org/combinators/solitaire/stalactites/Stalactites.java

run-stalactites: stalactites
	java -cp standAlone.jar:./stalactites/src/main/java org/combinators/solitaire/stalactites/Stalactites

.PHONY: idiot
idiot: idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java
	javac -cp standAlone.jar:./idiot/src/main/java idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java

run-idiot: idiot
	java -cp standAlone.jar:./idiot/src/main/java org/combinators/solitaire/idiot/Idiot

.PHONY: archway
archway: archway/src/main/java/org/combinators/solitaire/archway/Archway.java
	javac -cp standAlone.jar:./archway/src/main/java archway/src/main/java/org/combinators/solitaire/archway/Archway.java

run-archway: archway
	java -cp standAlone.jar:./archway/src/main/java org/combinators/solitaire/archway/Archway
