.PHONY: archway
archway: archway/src/main/java/org/combinators/solitaire/archway/Archway.java
        javac -cp standAlone.jar:./archway/src/main/java archway/src/main/java/org/combinators/solitaire/archway/Archway.java

run-archway: archway
        java -cp standAlone.jar:./archway/src/main/java org/combinators/solitaire/archway/Archway



.PHONY: bigforty
bigforty: bigforty/src/main/java/org/combinators/solitaire/bigforty/BigForty.java
        javac -cp standAlone.jar:./bigforty/src/main/java klondike/src/main/java/org/combinators/solitaire/bigforty/BigForty.java

run-bigforty: bigforty
        java -cp standAlone.jar:./bigforty/src/main/java org/combinators/solitaire/bigforty/BigForty




.PHONY: castle
castle: castle/src/main/java/org/combinators/solitaire/castle/Castle.java
        javac -cp standAlone.jar:./castle/src/main/java castle/src/main/java/org/combinators/solitaire/castle/Castle.java

run-castle: castle
        java -cp standAlone.jar:./castle/src/main/java org/combinators/solitaire/castle/Castle



.PHONY: freecell
freecell: freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java
        javac -cp standAlone.jar:./freecell/src/main/java freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java

run-freecell: freecell
        java -cp standAlone.jar:./freecell/src/main/java org/combinators/solitaire/freecell/FreeCell


.PHONY: idiot
idiot: idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java
        javac -cp standAlone.jar:./idiot/src/main/java idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java

run-idiot: idiot
        java -cp standAlone.jar:./idiot/src/main/java org/combinators/solitaire/idiot/Idiot



.PHONY: klondike
klondike: klondike/src/main/java/org/combinators/solitaire/klondike/Klondike.java
        javac -cp standAlone.jar:./klondike/src/main/java klondike/src/main/java/org/combinators/solitaire/klondike/Klondike.java

run-klondike: klondike
        java -cp standAlone.jar:./klondike/src/main/java org/combinators/solitaire/klondike/Klondike



.PHONY: narcotic
narcotic: narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java
        javac -cp standAlone.jar:./narcotic/src/main/java narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java

run-narcotic: narcotic
        java -cp standAlone.jar:./narcotic/src/main/java org/combinators/solitaire/narcotic/Narcotic

