.PHONY: archway
archway: solitaire/archway/src/main/java/org/combinators/solitaire/archway/Archway.java
	javac -cp standAlone.jar:./solitaire/archway/src/main/java solitaire/archway/src/main/java/org/combinators/solitaire/archway/Archway.java
run-archway:
	java -cp standAlone.jar:./solitaire/archway/src/main/java org/combinators/solitaire/archway/Archway

.PHONY: bigforty
bigforty: solitaire/bigforty/src/main/java/org/combinators/solitaire/bigforty/BigForty.java
	javac -cp standAlone.jar:./solitaire/bigforty/src/main/java solitaire/bigforty/src/main/java/org/combinators/solitaire/bigforty/BigForty.java
run-bigforty: bigforty
	java -cp standAlone.jar:./solitaire/bigforty/src/main/java org/combinators/solitaire/bigforty/BigForty

.PHONY: castle
castle: solitaire/castle/src/main/java/org/combinators/solitaire/castle/Castle.java
	javac -cp standAlone.jar:./solitaire/castle/src/main/java solitaire/castle/src/main/java/org/combinators/solitaire/castle/Castle.java
run-castle: castle
	java -cp standAlone.jar:./solitaire/castle/src/main/java org/combinators/solitaire/castle/Castle

.PHONY: freecell
freecell: solitaire/freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java
	javac -cp standAlone.jar:./solitaire/freecell/src/main/java solitaire/freecell/src/main/java/org/combinators/solitaire/freecell/FreeCell.java
run-freecell: freecell
	java -cp standAlone.jar:./solitaire/freecell/src/main/java org/combinators/solitaire/freecell/FreeCell

.PHONY: idiot
idiot: solitaire/idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java
	javac -cp standAlone.jar:./solitaire/idiot/src/main/java solitaire/idiot/src/main/java/org/combinators/solitaire/idiot/Idiot.java
run-idiot: idiot
	java -cp standAlone.jar:./solitaire/idiot/src/main/java org/combinators/solitaire/idiot/Idiot

.PHONY: klondike
klondike: solitaire/klondike/src/main/java/org/combinators/solitaire/klondike/Klondike.java
	javac -cp standAlone.jar:./solitaire/klondike/src/main/java solitaire/klondike/src/main/java/org/combinators/solitaire/klondike/Klondike.java
run-klondike: klondike
	java -cp standAlone.jar:./solitaire/klondike/src/main/java org/combinators/solitaire/klondike/Klondike

.PHONY: narcotic
narcotic: solitaire/narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java
	javac -cp standAlone.jar:./solitaire/narcotic/src/main/java solitaire/narcotic/src/main/java/org/combinators/solitaire/narcotic/Narcotic.java

run-narcotic: narcotic
	java -cp standAlone.jar:./solitaire/narcotic/src/main/java org/combinators/solitaire/narcotic/Narcotic

